# Generated by Django 4.1 on 2022-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(
                blank=True, default="default_room.jpg", null=True, upload_to=""
            ),
        ),
    ]
