# Generated by Django 4.1 on 2022-08-23 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile_image"),
        ("base", "0008_alter_room_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("sold", models.BooleanField(blank=True, default=False, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("gamername", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.IntegerField(blank=True, default=0, null=True)),
                ("accountlevel", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.profile",
                    ),
                ),
            ],
        ),
    ]
