# Generated by Django 4.1 on 2022-08-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="buyer",
            field=models.CharField(default="No Buyer", max_length=100),
        ),
    ]
