# Generated by Django 4.1 on 2022-08-04 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_profile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="discord",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name="CompRank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("game_name", models.CharField(blank=True, max_length=100, null=True)),
                ("rank", models.CharField(blank=True, max_length=100, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.profile",
                    ),
                ),
            ],
        ),
    ]
